debug-mode: true

invite-time: 5
banner-change-price: 5000
banner-price: 1000
guild-name-length: 15


guild-points:
  0:
    color-tag: "&7"
  10:
    color-tag: "&2"

banner-locations:
  world: WORLD
  leaderboard:
    1:
      loc: X,Y,Z

guild-scroll:
  glow: true
  name: "&dLonca Parşomeni"
  type: MAP
  lore:
    - "&7&oTek Kullanımlık"
    - ""
    - "&dLonca Parşomen"
    - ""